version: 0.0
os: linux
files:
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy_k8s.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/verify_deploy.sh
      timeout: 300
      runas: root

